ocl: workaround for msvc11 bug
"#error" requires DOS line endings (or fails with fatal error C1004: unexpected end-of-file found)
See: http://connect.microsoft.com/VisualStudio/feedback/details/794991/c-error-directive-and-unix-line-endings-leads-to-an-unexpected-end-of-file
So replace them to #pragma message.